language: python
sudo: false

matrix:
  include:
    - python: "2.7"
      dist: xenial
      sudo: true
    - python: "3.7"
      dist: xenial
      sudo: true

install:
  - python setup.py install
  - pip install coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
    - export TARGET="-m json_processor.test.runtests"
    - coverage run $TARGET
